name: focustify
description: "A simple focus app with to-do list and app shortcuts."
publish_to: 'none'

version: 1.0.1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  window_manager: ^0.4.3
  shared_preferences: ^2.5.2
  webview_windows: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
